### ISSUE TITLE
Errors when using any explorer besides SliceSampler() on a turing model

### ISSUE THREAD

**Issue by Raoul-Kima** [Julia-Tempering/Pigeons.jl#204]
When I try to use any explorer other then SliceSampler I get an error saying:
`KeyError: key :singleton_variable => OnlineStatsBase.Variance not found`

Here's a stacktrace from AutoMALA:
![image](https://github.com/Julia-Tempering/Pigeons.jl/assets/23742480/b36679b7-c422-4d2a-aa2d-5048a07f029a)

Test model was:
![image](https://github.com/Julia-Tempering/Pigeons.jl/assets/23742480/221fae1f-2ffc-4e68-85e5-42c27002d197)

Explorers tested were: AAPS, MALA, AutoMALA.

Here's the environment and reprex:
[alternativeSamplersTestReprex.zip](https://github.com/Julia-Tempering/Pigeons.jl/files/14282473/alternativeSamplersTestReprex.zip)

**Comment by alexandrebouchard** [comment]
Yes, the Pigeons-Turing integration currently support only the SliceSampler. We hope to relax this restriction soon. Note however that the slice sampler is more general since it handles both discrete and continuous variables. If performance is critical, for now it may be better to code the target in Stan, or as a Julia function as a workaround. For these types of target, AAPS, MALA, AutoMALA do work.

**Comment by Raoul-Kima** [comment]
Thanks for the clarification!
Shall I close this issue then, or leave it open for others so they can see it's known and being worked on?

**Comment by miguelbiron** [comment]
No worries! This issue is already tracked by #160 so feel free to close this one.
