### ISSUE TITLE
Question about slice sampler paper

### ISSUE THREAD

**Issue by trevorcampbell** [Julia-Tempering/Pigeons.jl#63]
https://projecteuclid.org/journals/annals-of-statistics/volume-31/issue-3/Slice-sampling/10.1214/aos/1056562461.full

On page 717, Fig. 6 -- it seems if D is set to true, it is never set to false again (even if the condition that set it true becomes false later on as you shrink the interval). It's probably not a bug and just something I'm misunderstanding, but it stood out to me as odd. 

(FWIW the current code in the repo implements what is written in the paper properly)

**Comment by alexandrebouchard** [comment]
That's a good question. I haven't contributed much to the Pigeons slice sampling code, so maybe this is fresher in Nikola's memory. But when I wrote the Blang code years ago I vaguely remember being puzzled by D as well. Unfortunately I can't locate my development notes from back then, but I did leave this comment:

```
// D in Neal's paper; whether the intervals generated by new and old differ; used for optimization
```

This makes me wonder if perhaps it is used so that when the conditional `D and ...` is evaluated, this is only an optimization so that the `...` bit is skipped? Haven't had a chance yet to double check if that's right. 

But I have an idea how we could check the correctness of the implementation (beyond Geweke), more on that later...

**Comment by trevorcampbell** [comment]
After spending a bit thinking about it, I think what's written in the paper is correct (unsurprisingly)

basically it tracks whether the new state is in the "same half" of the doubling procedure as the original point. If that is the case, there is no need to check the left/right potentials because the doubling procedure guarantees that at least one of y < f(L) or y < f(R) is true, and hence the check would not pass anyway.

**Comment by alexandrebouchard** [comment]
Awesome!

**Comment by miguelbiron** [comment]
I was following along this discussion yesterday, and kept trying to understand the "Accept(x1)" procedure. I wrote some notes which may serve someone else. Even though Neal also frames the D variable as basically for cost saving purposes, I think it is more fundamental than that.

The "Accept(x1)" algorithm in Fig 6 tests whether a doubling procedure initiated from x1 can build the exact same interval as the one found---i.e., (L,R)---by using the involution corresponding to the doubling that created (L,R) from x0.

The algorithm proceeds by contradiction, starting from the given interval and "undoing" a supposed doubling started from x1 that ends at (L,R) and contains x0. The magic of undoing a doubling is that it is a completely deterministic process, so we don't need to spell out the exact involution. Indeed, this is a way to prove that there is a unique combination of left-right growth decisions that generate any given interval via doubling starting from a known point.

The implicit involution is carried out simply by computing at each step the midpoint M, and then checking to which side x1 belongs in order to update (hL,hR). Note that when updating (hL,hR), x0 can then be left out of this interval---this is what D is checking.

```
hL             M                 hR
|         x0   |    x1           |
               hL'               hR'
```

The crucial point is that if this coincides with the termination criterion for the doubling algorithm---i.e., both hL and hR are outside the slice---then we have arrived at a contradiction: the undoing is not, in fact, an involution, since the doubling algorithm would have stopped at this point, with an interval (hL,hR) that does not contain x0. Hence, x1 needs to be discarded.

**Comment by nikola-sur** [comment]
Thanks for the comment, Miguel!

**Comment by alexandrebouchard** [comment]
Thanks Miguel! 

I agree, this procedure is definitely needed, sometimes it is called a "reversibility check" in the literature (although an "involution check" would be a better name I think). 

But do you agree that more specifically the variable D part is an optimization though, i.e. there would be a slightly simpler way to write the reversibility check?

**Comment by miguelbiron** [comment]
I suppose so. I mean, as long as at each halving step, you can verify the "contradiction clause"
```
x0∉[hL,hR] && !in_slice(hL) && !in_slice(hR)
```
then you should be in good shape.

**Comment by trevorcampbell** [comment]
> D = x0∉[hL,hR]

That's not quite right. D is tracking whether x0 is on the same side of M as x1. If at any point *it is not*, then x0 and x1 live on different parts of the binary tree *from that point downward*. But above that they exist on the same side, which is why you can skip the more detailed potential check (because it already passed on the way up while doubling)

**Comment by miguelbiron** [comment]
When I say that `D = x0∉[hL,hR]` I assume the halving already occured. The "other side" stuff is for checking  `x0∉[hL,hR]` *before* halving , but it is equivalent to checking it *after halving* by simply setting `D = x0∉[hL,hR]`.
![Screenshot_20230502-103227_pCloud](https://user-images.githubusercontent.com/11068143/235742663-45696106-af42-4835-a986-9d3dcd6eb318.jpg)

**Comment by trevorcampbell** [comment]
yep, see above. already edited my own comment ;)

**Comment by miguelbiron** [comment]
> You could implement it entirely correctly without D.

Not really is my point. You still need to check the contradiction clause, which includes assessing if `x0∉[hL,hR]`---which is exactly equal to D after halving.

**Comment by trevorcampbell** [comment]
I disagree. You don't need to know where x0 is when you're deciding whether x1 could have generated the same interval. You just need to know whether you "would have made it" to the same doubling step without terminating earlier. You can know that by just checking the potential at the endpoints as you shrink down to x1.

**Comment by miguelbiron** [comment]
The last sentence is where I think you're wrong. The fact that it is possible to have x0∉[hL,hR] tells you that the sequence of intervals in this algorithm are in general very different from the ones constructed starting from x0. So you cannot reuse those tests at all.

More importantly, the test is *not*

"Check if you would've stopped doubling from x1 before getting to the interval built from x0"

It is

"Check that any time you would've stopped in the doubling started from x1, x0 would've been inside [hL,hR]"

This forces the involution, since you would still be able to get x0 even if you stopped before getting to the full interval grown from x0.
