### ISSUE TITLE
copy for traces assumes copy() exists for the given state

### ISSUE THREAD

**Issue by nikola-sur** [Julia-Tempering/Pigeons.jl#74]
See
https://github.com/Julia-Tempering/Pigeons.jl/blob/a3afb4f339ff2f2917b7c2be82ce85884792a489/src/pt/pigeons.jl#L117-L119
This seems to assume that copy() is defined for the `state`, but it is not true for DynamicPPL NamedTuples and a state that I recently introduced for Stan models (`StanState`).

**Comment by nikola-sur** [comment]
It should be easy to define `copy()` for each of the non-vector states, but maybe we should make this a requirement in `state.jl`?

**Comment by ptiede** [comment]
We can't define `copy` for things like NamedTuples. That would be type piracy https://docs.julialang.org/en/v1/manual/style-guide/#Avoid-type-piracy and can be quite bad. If we need a copy like function we need to define our own copy function. We should probably do this anyways because copy may not have the semantics we want.

**Comment by alexandrebouchard** [comment]
Good point. Instead of copy() it is now extract_sample() which has been documented in the state interface.
